name: pink_bench
channels:
    - conda-forge
dependencies:
    - loop-rate-limiters >=0.1.0
    - matplotlib
    - meshcat-shapes >=0.3.0
    - pink >=3.1.0
    - qpmpc >=2.6.3
    - qpsolvers >=4.3.1
    - robot_descriptions >=1.13.0
